# Generated by Django 3.2.3 on 2021-06-12 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_auto_20210612_1350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Производители'},
        ),
    ]
