# Generated by Django 3.2.3 on 2021-06-12 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_auto_20210612_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Тип машины',
                'verbose_name_plural': 'Типы машин',
            },
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car.cartype'),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
